apiVersion: v1
kind: Service
metadata:
  name: weather-svc
spec:
  type: LoadBalancer
  selector:
    app: weather_app
  ports:
    - name: weather-port
      port: 8000
      nodePort: 30100
      targetPort: 8000